### ISSUE TITLE
ARM build

### ISSUE THREAD

**Issue by hansmbakker** [dotMorten/IoTivityDotNet#2]
I think you need the following in vc.py, because otherwise you'll generate x86 binaries for arm:

```python
# Dict to 'canonalize' the arch
_ARCH_TO_CANONICAL = {
    "amd64"     : "amd64",
    "emt64"     : "amd64",
    "i386"      : "x86",
    "i486"      : "x86",
    "i586"      : "x86",
    "i686"      : "x86",
    "ia64"      : "ia64",
    "itanium"   : "ia64",
    "x86"       : "x86",
    "x86_64"    : "amd64",
    "x86_amd64" : "x86_amd64",
    "arm"       : "arm"
}

# Given a (host, target) tuple, return the argument for the bat file. Both host
# and targets should be canonalized.
_HOST_TARGET_ARCH_TO_BAT_ARCH = {
    ("x86", "x86"): "x86",
    ("x86", "amd64"): "x86_amd64",
    ("x86", "x86_amd64"): "x86_amd64",
    ("amd64", "x86_amd64"): "x86_amd64", # This is present in (at least) VS2012 express
    ("amd64", "amd64"): "amd64",
    ("amd64", "x86"): "x86",
    ("x86", "ia64"): "x86_ia64",
    ("x86", "arm"): "x86_arm",
    ("amd64", "arm"): "amd64_arm"
}
```

However I had trouble testing it since Scons doesn't support VS2017 and it is quite hard to add it yourself (VS2017 has a different way of being discovered and doesn't have the same environment variables)

**Comment by hansmbakker** [comment]
I installed VS2015. However, when trying to build arm, I get:
```
C:\Program Files (x86)\Windows Kits\10\include\10.0.14393.0\ucrt\corecrt.h(226): fatal error C1189: #error:  Compiling Desktop applications for the ARM platform is not supported.
```

Apparently there is a ```/ZH``` compiler flag for WinRT/arm, but maybe it is good to look at what Microsoft did - they is completely bypassed Scons and created WinRT components for the OIC stack (see https://github.com/ms-iot/samples/tree/develop/AllJoyn/Samples/OICAdapter/OICStackRuntime). However that was for iotivity 1.0.0, I'm not sure whether that'll work out for 1.2.1 (I tried and got stuck in a hell of cross-references, maybe that is my lack of experience with VC++).

**Comment by hansmbakker** [comment]
@dotMorten have you found out anything new about this?

**Comment by TheSuperShoe** [comment]
@wind-rider @dotMorten  I was able to get around the "ARM platform is not supported" error by adding a couple of arguments to a SConscript file.

In the iotivity\build_common\windows\SConscripts file, add the argument:

'/D_ARM_WINAPI_PARTITION_DESKTOP_SDK_AVAILABLE'

to an env.AppendUnique(CCFLAGS = []) call.
I put it in the one on line 26.

So, Line 26 looks like:
env.AppendUnique(CCFLAGS = ['/EHsc',  '/D_ARM_WINAPI_PARTITION_DESKTOP_SDK_AVAILABLE'])

But with that, I still get an error on compile:
LINK: fatal error LNK1181: cannot open input file 'bcrypt.lib'

**Comment by dotMorten** [comment]
You're already miles ahead of me. I don't see any indication in the IoTivity history that ARM builds have been enabled yet. Perhaps @danmihai1 have some insights he can share

**Comment by TheSuperShoe** [comment]
I was able to get it to build for ARM.  Whether it works or not, I'm not sure.
You can checkout the changes from my fork and follow the directions from @wind-rider 's first post and it should build.  I'm not sure how I got around the bcrypt issue, it just started working. But the last note I had was that you have to set TEST to 0 in the BuildIotivity.cmd to build ARM.  Otherwise, it'll try to run an .exe file built for ARM, obviously fail, then stop building.

I've included the library I built in my fork too, incase you don't want to deal with building it.

**Comment by hansmbakker** [comment]
@TheSuperShoe for me it works!
The only thing missing in your fork are the copy rules for ARM in https://github.com/TheSuperShoe/IoTivityDotNet/blob/master/src/TestApps/TestApp.UWP/DeployNativeResources.targets. Other than that, it works!

@dotMorten could you please update your nuget packages with the dll from @TheSuperShoe?

**Comment by josephlm** [comment]
Thanks for this guys! I was able to get a build for the C SDK library (i.e. octbstack.dll) for Raspberry Pi from this information. I hope to see this information and possibly the fixes posted back to both SCons and IoTivity open source projects!

**Comment by dotMorten** [comment]
Thanks. Sorry need to get back into building but was trying to get back to using just VS2017 and not having to install 2015 too. I'll try and update in the next few days, but really you shouldn't use my binaries - they are usually immediately outdated every day since IoTivity changes so frequently

**Comment by hansmbakker** [comment]
That would be great, thanks! And optionally, for starters it might also be fine to add @thesupershoe 's binaries to your existing library?

I saw your mails on the iotivity-dec mailing list, I hope that works.

About iotivity changing every day - what do you mean exactly? I thought they have tagged releases that could be taken, which don't follow up each other that often?

**Comment by dotMorten** [comment]
Looks like IoTivity has ARM support now, so closing this.
