### ISSUE TITLE
Exception in Client.cs

### ISSUE THREAD

**Issue by hansmbakker** [dotMorten/IoTivityDotNet#3]
I had to put a try-catch around https://github.com/dotMorten/IoTivityDotNet/blob/master/src/TestApps/TestApp.NET45/Client.cs#L47-L60 because I always get a System.Exception in the client.GetAsync:

```
System.Exception: 'Resource returned error: OC_STACK_UNAUTHORIZED_REQ'
```

I don't know where the error comes from; I only get this error in the UWP app, both on x64 and on ARM (using the dll from @TheSuperShoe)

**Comment by TheSuperShoe** [comment]
I see this error too.  I put the try/catch in my repo.  It seems to run fine with it like this, but I'd like a more concrete fix.
OCEnums.cs says:
` /** Request is not authorized by Resource Server. */`
I'm new to IoTivity, so I don't know what all this means.

**Comment by hansmbakker** [comment]
Maybe this page can help us further: https://wiki.iotivity.org/security_resource_manager

I read it while sitting in public transport so couldn't look for the details but things we can check are
- does this article apply to the iotivity version we use?
- is security enabled in iotivity (compile flag)? -> I see SECURED=1 in the build script, so yes
- is persistent storage initialized correctly? -> I see that the persistent storage configuration is called and didn't see errors coming from there
- do we need such an "initial settings file"?
- is OC_SECURE set for the resource that was being queried?

**Comment by hansmbakker** [comment]
Another thing we can try is to use the client from here with a server sample from the iotivity distribution, or a client from the iotivity distribution with the server from here.

**Comment by TheSuperShoe** [comment]
I think you're right on the security.  I've update my code to print the device and the error.  All of the simulated devices are causing the error.  I built the libraries with SECURITY=0 and I get the same error.

**Comment by hansmbakker** [comment]
@TheSuperShoe thank you for trying. Do you have any other ideas what we could try? I'm a bit out of ideas (trying with oic_svr.dat didn't help)...

@dotMorten when you were writing this code, were you able to start observing resources, or to modify them? Do you have any ideas?

**Comment by dotMorten** [comment]
This is all really really rough test code right now. It's a little early to be reporting bugs in my test code - let's focus on just the API for now
