### ISSUE TITLE
AccessViolationException when running as a Background App for IoT Core (but the UWP app works fine)

### ISSUE THREAD

**Issue by hansmbakker** [dotMorten/IoTivityDotNet#5]
When creating a new Background App (IoT Core) as a test app, I get a `System.AccessViolationException` in IoTivityDotNet\Service.cs [at line 106](https://github.com/dotMorten/IoTivityDotNet/blob/master/src/IotivityDotNet/Service.cs#L106) ('Attempted to read or write protected memory. This is often an indication that other memory is corrupt.').

Steps to reproduce:

1. Clone repo from #4 
2. Add Background App (IoT core)
3. Add Class library (Universal Windows Platform) and link Server.cs and Log.cs to it. This is needed because in the Background app you can only use sealed classes.
4. Add references to IoTivityDotNet and IoTivityDotNet.Interop for both the background app and the class library
5. Add a reference to the class library in the background app
6. Add the UWP version of DeployNativeResources.targets to the background app project and add the appropriate Import Project element to its csproj file
7. Add the following code in the StartupTask

```csharp
public sealed class StartupTask : IBackgroundTask
    {

        static Server server;

        public void Run(IBackgroundTaskInstance taskInstance)
        {
            // 
            // TODO: Insert code to perform background work
            //
            // If you start any asynchronous methods here, prevent the task
            // from closing prematurely by using BackgroundTaskDeferral as
            // described in http://aka.ms/backgroundtaskdeferral
            //
        
            Debug.WriteLine("Initializing...");
            //EnableAggressiveGC();

            StorageFolder localFolder = ApplicationData.Current.LocalFolder;
            IotivityDotNet.Service.Initialize(IotivityDotNet.ServiceMode.ClientServer, localFolder.Path);
            IotivityDotNet.Service.SetDeviceInfo(".NET Console Test App", new string[] { "oic.wk.d" }, null, null);
            Log.OnLogEvent += (s, e) => Debug.WriteLine(e);

            Debug.WriteLine("Creating devices...");
            server = new Server();
                        
            Debug.WriteLine("Service running. Press any key to close\n");

            Debug.WriteLine("Shutting down...");
            server.Dispose();

            IotivityDotNet.Service.Shutdown().Wait();
            running = false;
        }

        //Loop for stressing the GC to ensure handles are released (don't do this outside testing!)
        static bool running = true;
        private static void EnableAggressiveGC()
        {
            Task.Run(async () =>
            {
                while (running)
                {
                    await Task.Delay(1000);
                    GC.Collect();
                    GC.WaitForPendingFinalizers();
                };
            });
        }
    }
```

**Comment by wind-rider** [comment]
It turns out that UWP app broke as well - there the AccessViolationException is thrown at [line 33](https://github.com/dotMorten/IoTivityDotNet/blob/master/src/IotivityDotNet/Service.cs#L33)
(using the latest binaries from #4). @TheSuperShoe have you noticed this?

**Comment by wind-rider** [comment]
The strange thing is that the TestApp.UWP sample still works, and that the TestApp.NET45 stopped working (although it worked before).

**Comment by wind-rider** [comment]
Never mind. I deleted the repo, cloned it again and now it works again. Don't know why.

**Comment by hansmbakker** [comment]
For a while I had a similar error with the TestApp.NET45 sample (there the AccessViolationException was thrown at [line 33](https://github.com/dotMorten/IoTivityDotNet/blob/master/src/IotivityDotNet/Service.cs#L33) but that solved itself when I deleted the local checkout and cloned the repo from #4 again.

Unfortunately the issue in the Background App remained, so I reopened the issue.

**Comment by hansmbakker** [comment]
It turns out the AccessViolationException in TestApp.NET45 on line 33 in Service.cs was thrown when I put a pre-generated oic_svr_db.dat from https://github.com/iotivity/iotivity/tree/master/resource/csdk/stack/samples/linux/secure in the folder, because I wanted to experiment with the security settings. Replacing the oic_svr_db.dat with any of the oic_svr_db_server dat files from that repo makes the NET45 and UWP sample crash.

However, I have not done this for the Background App, so there something else must be wrong. Also, the exception is thrown on another call there.
