### ISSUE TITLE
Progress?

### ISSUE THREAD

**Issue by hansmbakker** [dotMorten/IoTivityDotNet#6]
@dotMorten [on Twitter](https://twitter.com/dotmorten/status/928112501526425601) and [on the IoTivity mailing list](https://lists.iotivity.org/pipermail/iotivity-dev/2017-November/008624.html) I saw that you succeeded in getting it to work, congratulations! Is there anything you could show or share about it?

**Comment by dotMorten** [comment]
There's progress, but it's slow. When I said "succeeded" I really just meant that I got a few calls to go through successfully to the C-API from both .NET452 and Xamarin.Android, and even partially got some device discovery to work.
A fully working usable API is still quite far off, but this is a great start.

(I just pushed up what I got so far)
